// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Repository;

#nullable disable

namespace HamsterWarsV2API.Migrations
{
    [DbContext(typeof(RepositoryContext))]
    [Migration("20220602152327_InitialMigration")]
    partial class InitialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Entities.Models.Battle", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("Loser_ID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("Winner_ID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("Battles");
                });

            modelBuilder.Entity("Entities.Models.Hamster", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("HamsterId");

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<int>("Defeats")
                        .HasColumnType("int");

                    b.Property<string>("FavouriteActivity")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("FavouriteFood")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("Games")
                        .HasColumnType("int");

                    b.Property<string>("ImageName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Likes")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Wins")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Hamsters");

                    b.HasData(
                        new
                        {
                            Id = new Guid("3d490a70-94ce-4d15-9494-5244280c2ce3"),
                            Age = 1,
                            Defeats = 32,
                            FavouriteActivity = "Nothing",
                            FavouriteFood = "Nothing",
                            Games = 71,
                            ImageName = "hamster-1.jpg",
                            Likes = 348,
                            Name = "Haskel",
                            Status = "Active",
                            Wins = 39
                        },
                        new
                        {
                            Id = new Guid("3d590a70-94ce-4d15-9494-5244280c2ce3"),
                            Age = 1,
                            Defeats = 29,
                            FavouriteActivity = "Nothing",
                            FavouriteFood = "Beaver",
                            Games = 124,
                            ImageName = "hamster-2.jpg",
                            Likes = 553,
                            Name = "Shanon",
                            Status = "Active",
                            Wins = 95
                        },
                        new
                        {
                            Id = new Guid("3d590a70-94ce-4d15-9494-5244280a2ce3"),
                            Age = 0,
                            Defeats = 8,
                            FavouriteActivity = "Nothing",
                            FavouriteFood = "Chestnut",
                            Games = 97,
                            ImageName = "hamster-3.jpg",
                            Likes = 595,
                            Name = "Jedediah",
                            Status = "Active",
                            Wins = 89
                        },
                        new
                        {
                            Id = new Guid("3d590a70-94aa-4d15-9494-5244280a2ae3"),
                            Age = 1,
                            Defeats = 82,
                            FavouriteActivity = "Nothing",
                            FavouriteFood = "Cow",
                            Games = 166,
                            ImageName = "hamster-4.jpg",
                            Likes = 38,
                            Name = "Ruttger",
                            Status = "Active",
                            Wins = 84
                        },
                        new
                        {
                            Id = new Guid("3d590a70-94ce-4d15-9494-5244280a2aa3"),
                            Age = 2,
                            Defeats = 35,
                            FavouriteActivity = "Nothing",
                            FavouriteFood = "Nothing",
                            Games = 115,
                            ImageName = "hamster-5.jpg",
                            Likes = 689,
                            Name = "Eleanor",
                            Status = "Active",
                            Wins = 80
                        },
                        new
                        {
                            Id = new Guid("3d590a70-94ce-4d15-9794-5244280a2ab3"),
                            Age = 2,
                            Defeats = 56,
                            FavouriteActivity = "Nothing",
                            FavouriteFood = "Skunk",
                            Games = 109,
                            ImageName = "hamster-6.jpg",
                            Likes = 690,
                            Name = "Aggi",
                            Status = "Active",
                            Wins = 53
                        },
                        new
                        {
                            Id = new Guid("3f590a70-94ce-4d15-9494-5244280a2ac3"),
                            Age = 2,
                            Defeats = 105,
                            FavouriteActivity = "Nothing",
                            FavouriteFood = "Sloth",
                            Games = 155,
                            ImageName = "hamster-7.jpg",
                            Likes = 394,
                            Name = "Wally",
                            Status = "Active",
                            Wins = 50
                        },
                        new
                        {
                            Id = new Guid("3d890a70-94ce-4d15-9494-5244280a2ad3"),
                            Age = 3,
                            Defeats = 69,
                            FavouriteActivity = "Nothing",
                            FavouriteFood = "Frogmouth",
                            Games = 94,
                            ImageName = "hamster-8.jpg",
                            Likes = 748,
                            Name = "Jackquelin",
                            Status = "Active",
                            Wins = 25
                        },
                        new
                        {
                            Id = new Guid("3d590e70-94ce-4d15-9494-5244280a2ae3"),
                            Age = 2,
                            Defeats = 22,
                            FavouriteActivity = "Nothing",
                            FavouriteFood = "Jaguar",
                            Games = 77,
                            ImageName = "hamster-9.jpg",
                            Likes = 990,
                            Name = "Rick",
                            Status = "Active",
                            Wins = 55
                        },
                        new
                        {
                            Id = new Guid("3d598a70-94cf-4d15-9494-5244280a2af3"),
                            Age = 3,
                            Defeats = 4,
                            FavouriteActivity = "Nothing",
                            FavouriteFood = "Caribou",
                            Games = 28,
                            ImageName = "hamster-10.jpg",
                            Likes = 133,
                            Name = "Tova",
                            Status = "Active",
                            Wins = 24
                        },
                        new
                        {
                            Id = new Guid("3d590a74-94ce-4d15-9494-5244280a2ba3"),
                            Age = 2,
                            Defeats = 24,
                            FavouriteActivity = "Nothing",
                            FavouriteFood = "Owl",
                            Games = 59,
                            ImageName = "hamster-11.jpg",
                            Likes = 945,
                            Name = "Bogart",
                            Status = "Active",
                            Wins = 35
                        },
                        new
                        {
                            Id = new Guid("3d590a70-94ce-5d15-9494-5244280a2bb3"),
                            Age = 3,
                            Defeats = 37,
                            FavouriteActivity = "Nothing",
                            FavouriteFood = "Snake",
                            Games = 102,
                            ImageName = "hamster-12.jpg",
                            Likes = 619,
                            Name = "Gregorius",
                            Status = "Active",
                            Wins = 65
                        },
                        new
                        {
                            Id = new Guid("3d590a70-94ce-4d15-9494-5245280a2bc3"),
                            Age = 2,
                            Defeats = 12,
                            FavouriteActivity = "Nothing",
                            FavouriteFood = "Warthog",
                            Games = 29,
                            ImageName = "hamster-13.jpg",
                            Likes = 889,
                            Name = "Vevay",
                            Status = "Active",
                            Wins = 17
                        },
                        new
                        {
                            Id = new Guid("3d590a70-64ce-4d15-9494-5244280a2be3"),
                            Age = 1,
                            Defeats = 44,
                            FavouriteActivity = "Nothing",
                            FavouriteFood = "Boar",
                            Games = 52,
                            ImageName = "hamster-14.jpg",
                            Likes = 93,
                            Name = "Danny",
                            Status = "Active",
                            Wins = 8
                        },
                        new
                        {
                            Id = new Guid("3d990a70-94ce-4d15-9494-5244280a2bf3"),
                            Age = 3,
                            Defeats = 23,
                            FavouriteActivity = "Nothing",
                            FavouriteFood = "Iguana",
                            Games = 122,
                            ImageName = "hamster-15.jpg",
                            Likes = 627,
                            Name = "Davide",
                            Status = "Active",
                            Wins = 99
                        },
                        new
                        {
                            Id = new Guid("3d590a70-94ce-4d15-9094-5244280a2ca3"),
                            Age = 2,
                            Defeats = 51,
                            FavouriteActivity = "Nothing",
                            FavouriteFood = "Hoffman",
                            Games = 96,
                            ImageName = "hamster-16.jpg",
                            Likes = 291,
                            Name = "Mariellen",
                            Status = "Active",
                            Wins = 45
                        },
                        new
                        {
                            Id = new Guid("3d590a70-94be-4d15-9494-5244280a2cb3"),
                            Age = 3,
                            Defeats = 45,
                            FavouriteActivity = "Nothing",
                            FavouriteFood = "Koala",
                            Games = 104,
                            ImageName = "hamster-17.jpg",
                            Likes = 496,
                            Name = "Kittie",
                            Status = "Active",
                            Wins = 59
                        },
                        new
                        {
                            Id = new Guid("3d590a70-94ce-4d15-9494-5244280a2cc3"),
                            Age = 3,
                            Defeats = 91,
                            FavouriteActivity = "Nothing",
                            FavouriteFood = "Eagle",
                            Games = 111,
                            ImageName = "hamster-18.jpg",
                            Likes = 329,
                            Name = "Steffi",
                            Status = "Active",
                            Wins = 20
                        },
                        new
                        {
                            Id = new Guid("3d590d70-94ce-4d15-9494-5244280a2ce3"),
                            Age = 0,
                            Defeats = 39,
                            FavouriteActivity = "Nothing",
                            FavouriteFood = "Duck",
                            Games = 50,
                            ImageName = "hamster-19.jpg",
                            Likes = 26,
                            Name = "Phedra",
                            Status = "Active",
                            Wins = 11
                        },
                        new
                        {
                            Id = new Guid("3d590e70-94ce-4d15-9494-5244280a2cf3"),
                            Age = 2,
                            Defeats = 91,
                            FavouriteActivity = "Nothing",
                            FavouriteFood = "Squirrel",
                            Games = 188,
                            ImageName = "hamster-20.jpg",
                            Likes = 598,
                            Name = "Artemas",
                            Status = "Active",
                            Wins = 97
                        },
                        new
                        {
                            Id = new Guid("3d590d70-94ce-4d15-9494-5244280a2da3"),
                            Age = 1,
                            Defeats = 74,
                            FavouriteActivity = "Nothing",
                            FavouriteFood = "Nothing",
                            Games = 139,
                            ImageName = "hamster-21.jpg",
                            Likes = 252,
                            Name = "Lilla",
                            Status = "Active",
                            Wins = 65
                        },
                        new
                        {
                            Id = new Guid("3d590d70-94ce-4d15-9494-5244280a2db3"),
                            Age = 2,
                            Defeats = 91,
                            FavouriteActivity = "Nothing",
                            FavouriteFood = "Nothing",
                            Games = 127,
                            ImageName = "hamster-22.jpg",
                            Likes = 705,
                            Name = "Westleigh",
                            Status = "Active",
                            Wins = 36
                        },
                        new
                        {
                            Id = new Guid("3d590d70-94ce-4d15-9494-5244280a2dc3"),
                            Age = 0,
                            Defeats = 82,
                            FavouriteActivity = "Nothing",
                            FavouriteFood = "Shrike",
                            Games = 135,
                            ImageName = "hamster-23.jpg",
                            Likes = 133,
                            Name = "Bobby",
                            Status = "Active",
                            Wins = 53
                        },
                        new
                        {
                            Id = new Guid("3d590d70-94ce-4d15-9494-5244280a2dd3"),
                            Age = 3,
                            Defeats = 41,
                            FavouriteActivity = "Nothing",
                            FavouriteFood = "Indian",
                            Games = 89,
                            ImageName = "hamster-24.jpg",
                            Likes = 95,
                            Name = "Karyl",
                            Status = "Active",
                            Wins = 48
                        },
                        new
                        {
                            Id = new Guid("3d590d70-94ce-4d15-9494-5244280a2de3"),
                            Age = 0,
                            Defeats = 40,
                            FavouriteActivity = "Nothing",
                            FavouriteFood = "Waxbill",
                            Games = 67,
                            ImageName = "hamster-25.jpg",
                            Likes = 251,
                            Name = "Meryl",
                            Status = "Active",
                            Wins = 27
                        },
                        new
                        {
                            Id = new Guid("3d590f70-94ce-4d15-9494-5244280a2df3"),
                            Age = 0,
                            Defeats = 83,
                            FavouriteActivity = "Nothing",
                            FavouriteFood = "Quillan",
                            Games = 118,
                            ImageName = "hamster-26.jpg",
                            Likes = 598,
                            Name = "Quillan",
                            Status = "Active",
                            Wins = 35
                        },
                        new
                        {
                            Id = new Guid("3d590f70-94ce-4d15-9494-5244280a2ea3"),
                            Age = 2,
                            Defeats = 105,
                            FavouriteActivity = "Nothing",
                            FavouriteFood = "Buttermilk",
                            Games = 134,
                            ImageName = "hamster-27.jpg",
                            Likes = 454,
                            Name = "Modesty",
                            Status = "Active",
                            Wins = 29
                        },
                        new
                        {
                            Id = new Guid("3d590f70-94ca-4d15-9494-5244280a2ab3"),
                            Age = 2,
                            Defeats = 27,
                            FavouriteActivity = "Nothing",
                            FavouriteFood = "Heron",
                            Games = 44,
                            ImageName = "hamster-28.jpg",
                            Likes = 834,
                            Name = "Mariette",
                            Status = "Active",
                            Wins = 17
                        },
                        new
                        {
                            Id = new Guid("3d590f70-94ce-4d15-9494-5244280a2ec3"),
                            Age = 0,
                            Defeats = 21,
                            FavouriteActivity = "Nothing",
                            FavouriteFood = "Kingfisher",
                            Games = 89,
                            ImageName = "hamster-29.jpg",
                            Likes = 969,
                            Name = "Dorothee",
                            Status = "Active",
                            Wins = 68
                        },
                        new
                        {
                            Id = new Guid("3d590e70-94ce-4d15-9494-5244280a2ee3"),
                            Age = 1,
                            Defeats = 82,
                            FavouriteActivity = "Nothing",
                            FavouriteFood = "Vulture",
                            Games = 132,
                            ImageName = "hamster-30.jpg",
                            Likes = 275,
                            Name = "Stevy",
                            Status = "Active",
                            Wins = 50
                        },
                        new
                        {
                            Id = new Guid("3d590e70-94ce-4d15-9494-5244280a2ef3"),
                            Age = 1,
                            Defeats = 78,
                            FavouriteActivity = "Nothing",
                            FavouriteFood = "Lizard",
                            Games = 113,
                            ImageName = "hamster-31.jpg",
                            Likes = 479,
                            Name = "Grayce",
                            Status = "Active",
                            Wins = 35
                        },
                        new
                        {
                            Id = new Guid("3d590e70-94ce-4d15-9494-5244280a2fa3"),
                            Age = 0,
                            Defeats = 49,
                            FavouriteActivity = "Jaeger",
                            FavouriteFood = "Jaeger",
                            Games = 117,
                            ImageName = "hamster-32.jpg",
                            Likes = 971,
                            Name = "Jaeger",
                            Status = "Active",
                            Wins = 68
                        },
                        new
                        {
                            Id = new Guid("3d590f70-94ee-4d15-9494-5244280a2fb3"),
                            Age = 2,
                            Defeats = 11,
                            FavouriteActivity = "Nothing",
                            FavouriteFood = "Weeper",
                            Games = 59,
                            ImageName = "hamster-33.jpg",
                            Likes = 907,
                            Name = "Gannon",
                            Status = "Active",
                            Wins = 48
                        },
                        new
                        {
                            Id = new Guid("3d590f70-94ce-4d15-9494-5244280a2fc3"),
                            Age = 1,
                            Defeats = 87,
                            FavouriteActivity = "Nothing",
                            FavouriteFood = "Bunting",
                            Games = 141,
                            ImageName = "hamster-34.jpg",
                            Likes = 315,
                            Name = "Burton",
                            Status = "Active",
                            Wins = 54
                        },
                        new
                        {
                            Id = new Guid("3d590f70-94ce-4d15-9494-5244280a2fd3"),
                            Age = 3,
                            Defeats = 54,
                            FavouriteActivity = "Nothing",
                            FavouriteFood = "Nothing",
                            Games = 139,
                            ImageName = "hamster-35.jpg",
                            Likes = 660,
                            Name = "Kaycee",
                            Status = "Active",
                            Wins = 85
                        },
                        new
                        {
                            Id = new Guid("3d590f70-94ce-4d15-9494-5244280a2fe3"),
                            Age = 0,
                            Defeats = 12,
                            FavouriteActivity = "Nothing",
                            FavouriteFood = "Bushbaby",
                            Games = 59,
                            ImageName = "hamster-36.jpg",
                            Likes = 819,
                            Name = "Allix",
                            Status = "Active",
                            Wins = 47
                        },
                        new
                        {
                            Id = new Guid("3d590f70-94ce-4d15-9494-5244280a2ff3"),
                            Age = 1,
                            Defeats = 70,
                            FavouriteActivity = "Nothing",
                            FavouriteFood = "Alpaca",
                            Games = 170,
                            ImageName = "hamster-37.jpg",
                            Likes = 10,
                            Name = "Herbert",
                            Status = "Active",
                            Wins = 100
                        },
                        new
                        {
                            Id = new Guid("3d590a70-94ce-4d15-9494-5244280a2fa3"),
                            Age = 0,
                            Defeats = 93,
                            FavouriteActivity = "Nothing",
                            FavouriteFood = "Fox",
                            Games = 164,
                            ImageName = "hamster-38.jpg",
                            Likes = 402,
                            Name = "Ginny",
                            Status = "Active",
                            Wins = 71
                        },
                        new
                        {
                            Id = new Guid("3d590a70-94ce-4d15-9494-5244280a2fb3"),
                            Age = 1,
                            Defeats = 20,
                            FavouriteActivity = "Nothing",
                            FavouriteFood = "Badger",
                            Games = 54,
                            ImageName = "hamster-39.jpg",
                            Likes = 122,
                            Name = "Teriann",
                            Status = "Active",
                            Wins = 34
                        },
                        new
                        {
                            Id = new Guid("3d590a70-94ce-4d15-9494-5244280a2fc3"),
                            Age = 3,
                            Defeats = 73,
                            FavouriteActivity = "Nothing",
                            FavouriteFood = "Nothing",
                            Games = 157,
                            ImageName = "hamster-40.jpg",
                            Likes = 76,
                            Name = "Shelia",
                            Status = "Active",
                            Wins = 84
                        },
                        new
                        {
                            Id = new Guid("3d590a70-94ce-4d15-9494-5244280a2fd3"),
                            Age = 8,
                            Defeats = 5,
                            FavouriteActivity = "Murder",
                            FavouriteFood = "Human",
                            Games = 934,
                            ImageName = "hamster-42.jpg",
                            Likes = 0,
                            Name = "Fuling",
                            Status = "Active",
                            Wins = 929
                        },
                        new
                        {
                            Id = new Guid("3d590a70-94ce-4d15-9494-5244280a2fe3"),
                            Age = 2,
                            Defeats = 1,
                            FavouriteActivity = "Dinner",
                            FavouriteFood = "See picture",
                            Games = 1008,
                            ImageName = "hamster-41.jpg",
                            Likes = 9999,
                            Name = "Evil",
                            Status = "Active",
                            Wins = 1007
                        },
                        new
                        {
                            Id = new Guid("3d590a70-94ce-4d15-9494-5244280a2ff3"),
                            Age = 0,
                            Defeats = 1,
                            Games = 1,
                            ImageName = "hamster-43.jpg",
                            Likes = 0,
                            Name = "test",
                            Status = "Deleted",
                            Wins = 0
                        },
                        new
                        {
                            Id = new Guid("3d590d70-94ce-4d15-9494-5244280a2ea3"),
                            Age = 0,
                            Defeats = 1,
                            Games = 1,
                            ImageName = "hamster-43.jpg",
                            Likes = 0,
                            Name = "test1",
                            Status = "Deleted",
                            Wins = 0
                        },
                        new
                        {
                            Id = new Guid("3d590d70-94ea-4d15-9494-5244280a2ae3"),
                            Age = 2,
                            Defeats = 0,
                            Games = 0,
                            ImageName = "hamster-43.jpg",
                            Likes = 0,
                            Name = "test2",
                            Status = "Deleted",
                            Wins = 0
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
